### ISSUE TITLE
circleci/hugo@1.3.0: `--error-sort` flag fails to build

### ISSUE THREAD

**Issue by justwheel** [CircleCI-Public/hugo-orb#51]
### Orb version

1.3.0

### What happened

The `--error-sort` flag behaves unexpectedly and fails the HTML-Proofer step when running a build. See a log [here](https://app.circleci.com/pipelines/github/sustainers/design/35/workflows/548c049a-6a70-4bdf-9e0b-be2f216cc45e/jobs/60).

Stacktrace for reference:

```ruby
Traceback (most recent call last):
	4: from /usr/local/bin/htmlproofer:23:in `<main>'
	3: from /usr/local/bin/htmlproofer:23:in `load'
	2: from /var/lib/gems/2.7.0/gems/html-proofer-3.19.3/bin/htmlproofer:11:in `<top (required)>'
	1: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
/var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:33:in `go': invalid argument: --error-sort  (OptionParser::InvalidArgument)
```

I guess my change in #47 was half-baked. 😞 Not sure how best to debug this one.

### Expected behavior

HTML-Proofer successfully validates the HTML according to user preference.

**Comment by justwheel** [comment]
It appears a [read-only key was used](https://app.circleci.com/pipelines/github/CircleCI-Public/hugo-orb/217/workflows/a771a1a5-773a-418b-a00f-764a7cacd465/jobs/506/parallel-runs/0/steps/0-107) in the [`orb-tools/dev-promote-prod-from-commit-subject`](https://app.circleci.com/pipelines/github/CircleCI-Public/hugo-orb/217/workflows/a771a1a5-773a-418b-a00f-764a7cacd465/jobs/506) job from the [`integration-tests_prod-release`](https://app.circleci.com/pipelines/github/CircleCI-Public/hugo-orb/217/workflows/a771a1a5-773a-418b-a00f-764a7cacd465) workflow. I don't think this is related to the HTML-Proofer error in the above stacktrace though.

**Comment by justwheel** [comment]
Any possibility this could be fixed? The orb is broken in the latest version. Or, if you have any pointers on how to fix it, I can try to make my own attempt at it.

**Comment by justwheel** [comment]
Since a lot of this trouble with `htmlproofer` appears to come from unexpected behavior by the `--error-sort` flag, I opened gjtorikian/html-proofer#701 to seek clarity on this upstream.

**Comment by Jaryt** [comment]
Looking into this now! Sorry for the delay

**Comment by justwheel** [comment]
@Jaryt Thank you. Please share an update here when a new version is published in the registry. I'll test a new release in the five Pull Requests referenced at the top of the issue.
